### PR TITLE
Fix mail compose window creation when using scene delegate

### LINKED ISSUE #104: Email bug reporter does not show mail composer in apps using scene delegate
In apps that use a [`UISceneDelegate`](https://developer.apple.com/documentation/uikit/uiscenedelegate), the `ARKEmailBugReporter` does not present the mail composer after completing the initial prompt.

### PR DESCRIPTION
**Pull request by NickEntin**
In apps that use a scene delegate, windows must be initialized using the window scene, rather than being initialized with a frame.

Resolves #104.

### CODE REVIEW

File: Sources/AardvarkMailUI/ARKEmailBugReporter.m [hunk 1]
```diff
@@ -472,7 +491,6 @@ - (void)_showEmailComposeWindow;
     [self.mailComposeViewController beginAppearanceTransition:YES animated:YES];
     
     self.emailComposeWindow.rootViewController = self.mailComposeViewController;
-    [self.emailComposeWindow addSubview:self.mailComposeViewController.view];
```
Comment (NickEntin) [inline Sources/AardvarkMailUI/ARKEmailBugReporter.m:475]: With this line here, we get a warning in the console:
```
[Window] Manually adding the rootViewController's view to the view hierarchy is no longer supported. Please allow UIWindow to add the rootViewController's view to the view hierarchy itself.
```
This lines up with the documentation for [UIWindow.rootViewController](https://developer.apple.com/documentation/uikit/uiwindow/1621581-rootviewcontroller):
```
Assigning a view controller to this property (either programmatically or using Interface Builder) installs the view controller’s view as the content view of the window.
```
I tested with this line removed on iOS 14, both in an app with and without a scene delegate, and it worked fine. I'll try it tomorrow on a device running an older version.

Comment (NickEntin) [reply Sources/AardvarkMailUI/ARKEmailBugReporter.m:475]: This works on my device running iOS 12.4.8

File: Sources/AardvarkMailUI/ARKEmailBugReporter.m [hunk 2]
```diff
@@ -330,6 +338,17 @@ - (NSString *)formattedLogMessagesAttachmentExtension;
 
 #pragma mark - Private Methods
 
+- (UIWindowScene *)_activeWindowScene API_AVAILABLE(ios(13.0));
```
Comment (efirestone) [inline Sources/AardvarkMailUI/ARKEmailBugReporter.m:341]: nit: Could be static.

**Review by efirestone — APPROVED** [review]

File: Sources/AardvarkMailUI/ARKEmailBugReporter.m (hunk 2 above)
Comment (NickEntin) [reply Sources/AardvarkMailUI/ARKEmailBugReporter.m:341]: Sure 👍
