### PR TITLE
Flush log observers after logging an uncaught exception

### LINKED ISSUE #68: Flush all log observers when logging an uncaught exception
Follow-up to #53 to also flush all observers, not just the distributor

### PR DESCRIPTION
**Pull request by NickEntin**
Resolves #68

### CODE REVIEW

File: Sources/CoreAardvark/Logging/ARKLogDistributor_Testing.h [hunk 1]
```diff
@@ -25,7 +25,6 @@
 
 @interface ARKLogDistributor (Private)
 
-- (nonnull NSMutableSet *)logObservers;
```
Comment (NickEntin) [inline Sources/CoreAardvark/Logging/ARKLogDistributor_Testing.h:28]: Doesn't seem like this ever should have worked, but... 🤷‍♂️

File: Sources/CoreAardvark/Logging/ARKDataArchive.m [hunk 2]
```diff
@@ -199,6 +199,19 @@ - (void)saveArchiveAndWait:(BOOL)wait;
...
+- (void)saveArchiveWithCompletionHandler:(nullable dispatch_block_t)completionHandler;
+{
+    NSBlockOperation *completionOperation = [NSBlockOperation blockOperationWithBlock:^{
+        [self.fileHandle synchronizeFile];
+
+        if (completionHandler != NULL) {
+            completionHandler();
+        }
+    }];
+    completionOperation.qualityOfService = NSQualityOfServiceUserInitiated;
```
Comment (dfed) [inline Sources/CoreAardvark/Logging/ARKDataArchive.m:211]: This a pretty intense QoS for something that's invisible to a customer. Might be good to add a comment as to why we're utilizing this QOS.

File: Sources/CoreAardvark/Logging/ARKExceptionLogging.m [hunk 3]
```diff
@@ -50,12 +51,25 @@ void ARKHandleUncaughtException(NSException *_Nonnull exception)
...
+            if ([observer respondsToSelector:@selector(processAllPendingLogsWithCompletionHandler:)]) {
+                dispatch_group_enter(observerGroup);
+                [observer processAllPendingLogsWithCompletionHandler:^{
+                    dispatch_group_leave(observerGroup);
+                }];
+            }
+        }
     }
 
+    dispatch_group_wait(observerGroup, DISPATCH_TIME_FOREVER);
```
Comment (dfed) [inline Sources/CoreAardvark/Logging/ARKExceptionLogging.m:71]: Please add a good comment explaining why we're waiting and also why waiting here is safe. Waiting means future contributors are going to be a bit scared to touch this code, especially given that we're in the midst of a lock. Let's help them.

File: Sources/CoreAardvark/Logging/ARKLogObserver.h [hunk 4]
```diff
@@ -33,4 +33,9 @@
 /// Called on a background operation queue when logs are appended to the log distributor.
 - (void)observeLogMessage:(nonnull ARKLogMessage *)logMessage;
 
+@optional
```
Comment (dfed) [inline Sources/CoreAardvark/Logging/ARKLogObserver.h:36]: oh wow I forgot this was a feature of Objective-C.

File: Sources/CoreAardvark/Logging/ARKDataArchive.m [hunk 5]
```diff
@@ -199,6 +199,19 @@ - (void)saveArchiveAndWait:(BOOL)wait;
     }
 }
 
+- (void)saveArchiveWithCompletionHandler:(nullable dispatch_block_t)completionHandler;
```
Comment (dfed) [inline Sources/CoreAardvark/Logging/ARKDataArchive.m:202]: add a test for this method?

File: Sources/CoreAardvark/Logging/ARKExceptionLogging.m [hunk 6]
```diff
@@ -50,12 +51,25 @@ void ARKHandleUncaughtException(NSException *_Nonnull exception)
     NSLock *const logDistributorsLock = ARKGetUncaughtExceptionLogDistributorsLock();
     [logDistributorsLock lock];
 
+    dispatch_group_t observerGroup = dispatch_group_create();
```
Comment (dfed) [inline Sources/CoreAardvark/Logging/ARKExceptionLogging.m:54]: is it possible for us to add unit tests to this method?

**Review by dfed — COMMENTED** [review]
Exciting! A bit more to do before I can approve though.

File: Sources/CoreAardvark/Logging/ARKDataArchive.m (hunk 2 above)
Comment (NickEntin) [reply Sources/CoreAardvark/Logging/ARKDataArchive.m:214]: Addressed in 0ad0e56.

File: Sources/CoreAardvark/Logging/ARKExceptionLogging.m (hunk 3 above)
Comment (NickEntin) [reply Sources/CoreAardvark/Logging/ARKExceptionLogging.m]: Added a note about why we're waiting in 80045c8.

I don't have a great answer for why (or if) it's safe to wait here. As far as I know, this shouldn't make things worse, but at this point the app is already in an unstable state, so it's hard to know for sure. I changed it to 30 seconds and moved the wait until after we unlock to avoid any potential deadlock there.

File: Sources/CoreAardvark/Logging/ARKLogObserver.h (hunk 4 above)
Comment (NickEntin) [reply Sources/CoreAardvark/Logging/ARKLogObserver.h:36]: Yep. 😄 It's great.

File: Sources/CoreAardvark/Logging/ARKExceptionLogging.m (hunk 6 above)
Comment (NickEntin) [reply Sources/CoreAardvark/Logging/ARKExceptionLogging.m:54]: I added a unit test in 454d943. I'm not sure a great way to test the timing of it, but the test at least confirms that the method is called.

File: Sources/CoreAardvark/Logging/ARKDataArchive.m (hunk 5 above)
Comment (NickEntin) [reply Sources/CoreAardvark/Logging/ARKDataArchive.m:202]: Added in 76e6099.

File: Sources/CoreAardvark/Logging/ARKExceptionLogging.m (hunk 6 above)
Comment (dfed) [reply Sources/CoreAardvark/Logging/ARKExceptionLogging.m:54]: I think that's reasonable!

**Review by dfed — APPROVED** [review]
